version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - API_HOST=0.0.0.0
      - API_PORT=5000
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - WORKER_ENABLED=True
      - SYNC_INTERVAL_CATEGORIES=3600
      - SYNC_INTERVAL_ASSETS=1800
      - SYNC_INTERVAL_CANDLES=60
      - SYNC_INTERVAL_CURRENT=1
      - CACHE_ENABLED=True
      - CACHE_TTL=300
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
      - ./export:/app/export
